### PR TITLE
Update changelog for this weekend's changes

### PR DESCRIPTION
**Pull request by Nidoxs**
# MERGE ONCE #103 & #105 ARE MERGED

Forgot to update the changelog during the changes we've been making this weekend! Let's fix that in this PR.

### CODE REVIEW

**Review by LastTalon — APPROVED** [review]

**Comment by Nidoxs** [comment]
Both of the pre-requisite PRs have been merged. 

Should be ready to merge this now! 🥳

**Comment by LastTalon** [comment]
Can you please move the parts for #110 and #113 to their respective PRs so that we can merge this for the ones that are already closed?

**Comment by Nidoxs** [comment]
> Can you please move the parts for #110 and #113 to their respective PRs so that we can merge this for the ones that are already closed?

@LastTalon Good to go!

**Review by LastTalon — APPROVED** [review]

**Comment by LastTalon** [comment]
Excellent. Merging.

**Pull request merged**
